server:
  port: ${config.server.port:7011}
spring:
  jersey:
    application-path: micromys/api
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://${config.database.url:127.0.0.1:3306}/micromys?autoReconnect=true&useSSL=false
    username: ${config.database.username:root}
    password: ${config.database.password:root}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    mongodb:
      uri: mongodb://${config.mongodb.uri:127.0.0.1:27017}/micromys
  redis:
    host: ${config.redis.host:127.0.0.1}
axon:
  serializer:
    events: jackson
# this serializer is not work
